# Generated by Django 3.1.1 on 2020-09-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
    ]
